Repository damncode12/devitup, pull requests merged in 2023-10, with the labels that each got.

#16 fix: Issue #1
  TanishqAgarwal/Contributor.txt
  TanishqAgarwal/DockX/README.md
  TanishqAgarwal/DockX/dockx/__init__.py
  TanishqAgarwal/DockX/dockx/__pycache__/cont.cpython-311.pyc
  TanishqAgarwal/DockX/dockx/__pycache__/launcher.cpython-311.pyc
  TanishqAgarwal/DockX/dockx/assets/047pegasus.jpg
  TanishqAgarwal/DockX/dockx/assets/FinalLogo.png
  TanishqAgarwal/DockX/dockx/assets/anim.gif
  TanishqAgarwal/DockX/dockx/assets/box.png
  TanishqAgarwal/DockX/dockx/assets/cloud.png
  TanishqAgarwal/DockX/dockx/assets/docker.png
  TanishqAgarwal/DockX/dockx/assets/docker_green.png
  TanishqAgarwal/DockX/dockx/assets/docker_greenjpg.jpg
  TanishqAgarwal/DockX/dockx/assets/docker_red.png
  TanishqAgarwal/DockX/dockx/assets/docker_redjpg.jpg
  TanishqAgarwal/DockX/dockx/assets/ethernet.png
  TanishqAgarwal/DockX/dockx/assets/favicon.ico
  TanishqAgarwal/DockX/dockx/assets/hard_drive.png
  TanishqAgarwal/DockX/dockx/assets/home.png
  TanishqAgarwal/DockX/dockx/assets/refresh.png
  TanishqAgarwal/DockX/dockx/assets/round.png
  TanishqAgarwal/DockX/dockx/assets/splash.png
  TanishqAgarwal/DockX/dockx/assets/statistics.png
  TanishqAgarwal/DockX/dockx/backend/gen.py
  TanishqAgarwal/DockX/dockx/cont.py
  TanishqAgarwal/DockX/dockx/imagetk_linux_sol.txt
  TanishqAgarwal/DockX/dockx/launcher.py
  TanishqAgarwal/DockX/dockx/main.py
  TanishqAgarwal/DockX/dockx/stats_gen.py
  TanishqAgarwal/DockX/poetry.lock
  TanishqAgarwal/DockX/pyproject.toml
  TanishqAgarwal/DockX/tests/__init__.py
Labels: hacktoberfest-accepted

#33 Done with the issue
  Chandrapal_Singh/contributor.txt
  Chandrapal_Singh/flipkartclone/Flipkart-logo.png
  Chandrapal_Singh/flipkartclone/Screenshot (8).png
  Chandrapal_Singh/flipkartclone/flipkart-095e08.svg
  Chandrapal_Singh/flipkartclone/index.css
  Chandrapal_Singh/flipkartclone/index.html
  Chandrapal_Singh/flipkartclone/logo.png
  Chandrapal_Singh/flipkartclone/logo1.jpg
  Chandrapal_Singh/flipkartclone/pic1.jpg
  Chandrapal_Singh/flipkartclone/pic10.webp
  Chandrapal_Singh/flipkartclone/pic11.webp
  Chandrapal_Singh/flipkartclone/pic12.webp
  Chandrapal_Singh/flipkartclone/pic15.jpeg
  Chandrapal_Singh/flipkartclone/pic16.jpeg
  Chandrapal_Singh/flipkartclone/pic17.jpeg
  Chandrapal_Singh/flipkartclone/pic18.jpeg
  Chandrapal_Singh/flipkartclone/pic19.jpeg
  Chandrapal_Singh/flipkartclone/pic2.webp
  Chandrapal_Singh/flipkartclone/pic20.jpeg
  Chandrapal_Singh/flipkartclone/pic21.webp
  Chandrapal_Singh/flipkartclone/pic22.webp
  Chandrapal_Singh/flipkartclone/pic23.webp
  Chandrapal_Singh/flipkartclone/pic24.webp
  Chandrapal_Singh/flipkartclone/pic26.webp
  Chandrapal_Singh/flipkartclone/pic27.webp
  Chandrapal_Singh/flipkartclone/pic28.webp
  Chandrapal_Singh/flipkartclone/pic29.webp
  Chandrapal_Singh/flipkartclone/pic3.webp
  Chandrapal_Singh/flipkartclone/pic5.webp
  Chandrapal_Singh/flipkartclone/pic6.webp
  Chandrapal_Singh/flipkartclone/pic7.webp
  Chandrapal_Singh/flipkartclone/pic8.webp
  Chandrapal_Singh/flipkartclone/pic9.webp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#34 Project Addition
  Ashish_Sri/Image to Pencil Sketch with Python.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#35 Create chess game on react
  Rahul_Jangra/chess.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added Python Scripts to Scrape data from Website
  Sathvik N G/orielly_website_crawler.py
  Sathvik N G/site_external_links_collector.py
Labels: hacktoberfest
